# -*- coding: utf-8 -*-
"""Time Table Generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zghESsN5ITs1zjo6awl_7ZBBafhxhe5
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

subjects_input=input("Enter subjects (comma seperated): ")
days_input = input("Enter days (comma seperated):")
periods_per_day = int(input("Enter number of periods per day: "))

subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days =  [d.strip() for d in days_input.split(",") if d.strip()]

if len(subjects) == 0 or len(days) == 0 or periods_per_day <=0:
  print("Invalid input. Please try again.")
else:
  timetable = {}

  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)

  df = pd.DataFrame(timetable)
  df.index = [f"Period {i+1}" for i in range(periods_per_day)]

  print("\nTimeTable Generated Successfully\n")
  display(df)

  df.to_csv("timetable.csv")
  print("\nTimetable saved as timetable.csv")